name: units
parameters: |
  __spring.xml=xharbor/xharbor.xml,http/httpclient.xml,http/httpserver.xml
children:
  - name: nettystats
  - name: redisclient
    parameters: |
      redis.server.hostname=localhost
      redis.server.passwd=passwd
      redis.server.dbno=255
  - name: jmxsrv
    parameters: |
      jmxmp.port = 0
      jmxhtml.port = 8083
  - name: nop.httpout
    children:
      - name: httpfeatures.compress
        parameters: |
          features.name=compress
        children:
          - name: feature_compress
          - name: feature_logging
      - name: httpfeatures.default
        parameters: |
          features.name=default
        children:
          - name: feature_logging
  - name: router.biz
    children:
      - name: nop.httpin
        children:
          - name: httpin.8888
            parameters: |
              http.port=8888
              http.address=127.0.0.1
          - name: httpin.8443_https
            parameters: |
              http.port=8443
              http.address=127.0.0.1
            children:
              - name: feature_ssl4server
      - name: rules.100
        parameters: |
          priority=100
        children:
          - name: respond.checkhealth
            parameters: |
              request.method=HEAD|GET
              request.path=^/$|/checkhealth
              response.status=200
          - name: forward.ydd
            parameters: |
              forward.path=/api1/[/|\\w]*\
                    |/api2/[/|\\w]*
              
              forward.to=http://api.iplusmed.com:80
              features.name=compress
          - name: forward.zkwebui
            parameters: |
              forward.path=/zkwebui/[/|\\w]*
              forward.to=http://127.0.0.1:7080
          - name: rwresp.cors
            parameters: |
              rewrite.path=/api1/(\\w)*
            children:
              - name: addheader.cors.basic
                parameters: |
                  header.name=Access-Control-Allow-Origin
                  header.value=*
  - name: router.console
    children:
      - name: httpin.8889
        parameters: |
          http.port=8889
      - name: rules.100
        parameters: |
          priority=100
        children:
          - name: forward.jmxhtml.self
            parameters: |
              forward.headers=x-jmx,jmxhtml.self
              forward.to=http://127.0.0.1:8083
          - name: rwreq.jmxhtml
            parameters: |
              rewrite.path=/jmxhtml[\\w|\\.]*
              rewrite.to=
              rewrite.header.name=x-jmx
              rewrite.header.value=jmxhtml.self
          - name: auth.jmxhtml
            parameters: |
              auth.headers=x-jmx,jmxhtml(\\w)*
              auth.user=test
              auth.password=test
              